### ISSUE TITLE
JSON to replace iframe

### ISSUE THREAD

**Issue by TeaWithLucas** [mivalsten/ddb-dm-screen#27]
I have done a similar project involving dnd stats, but I used the JSON that contains all the character data:
https://dev.fandom.com/wiki/MediaWiki:DnDBeyondAPI.js
I think this is a more efficient/accurate/elegant way of getting the data for each character.
The only information needed is the character ID, so its a simple to get the JSON data.
I'll have a play around with it, but putting this here if anyone wants to help

**Comment by mivalsten** [comment]
Hi Lucas,
This is actually how we did that in the v1, but decided against it as it required us to re-implement all the rules and mechanics. Now, by grabbing the data from calculated sheet we get numbers that are guaranteed to be correct.
Additionally, by grabing data from the sheet instead of JSON, we allow evryone with access to campaign page to use the DM screen, as JSONs are available only to character owners and campaign owners.
